sudo: false
language: scala
scala: 2.11.1
jdk: oraclejdk8

notifications:
  email: false
env:
  global: TERM=dumb

before_install: chmod +x gradlew
install: ./gradlew setupCIWorkspace
script: ./gradlew build